algoritmo "QUESTAO_05"
// Função :
// Autor :
// Data : 28/03/2022
// Seção de Declarações 
var
nome: caracter
n1,n2,n3,n4,media:real
inicio
// Seção de Comandos
escreval("Digite seu nome: ")
leia(nome)
escreval("Digite a nota N1: ")
leia(n1)
escreval("Digite a nota N2: ")
leia(n2)
escreval("Digite a nota N3: ")
leia(n3)
escreval("Digite a nota N4: ")
leia(n4)

media <- (n1+n2+n3+n4)/4

escreval("Olá ",nome)
escreval("Sua média é de: ",media)


fimalgoritmo
