algoritmo "CalculaMedia"
// Função : Calcular a média de 2 notas
// Autor : Prof. Anderson Vanin
// Data : 26/04/2022
// Seção de Declarações 
var
p1,p2,media:real
inicio
// DADOS DE ENTRADA
escreval("Entre com um valor para P1: ")
leia(p1)
escreval("Entre com um valor para P2: ")
leia(p2)
//FIM DOS DADOS DE ENTRADA

//PROCESSAMENTO
media <- (p1+p2)/2
//FIM DO PROCESSAMENTO

//DADOS DE SAÍDA
escreval("A média do aluno é: ",media)
//FIM DOS DADOS DE SAÍDA

fimalgoritmo
